version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=jamo
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: unless-stopped
    command:
      - -storageDataPath=/data
      - -retentionPeriod=30d
      - -httpListenAddr=:8428
    volumes:
      - ./data/metrics:/data
    ports:
      - "8428:8428"
    networks:
      - monitoring

  screeps-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: screeps-agent
    restart: unless-stopped
    environment:
      - SCREEPS_TOKEN=3ffb99b6-ecb0-45a3-9923-5945f0f17be5
      - VICTORIA_METRICS_URL=http://victoriametrics:8428
      - NODE_ENV=production
    depends_on:
      - victoriametrics
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
